---
name: Qwiet pre-zero

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  Qwiet-Static-Analysis:
    runs-on: ubuntu-latest
    container: shiftleft/core:latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v4

    # - name: Download ShiftLeft CLI
    #   run: |
    #     curl https://cdn.shiftleft.io/download/sl > ./sl && chmod a+rx ./sl 

    - name: Run sl analyze 1
      shell: bash
      run: |
        ./sl analyze --verbose --wait --app "${GITHUB_REPOSITORY_OWNER}_${GITHUB_REPOSITORY#*/}" .
        sl analyze --verbose --app "${GITHUB_REPOSITORY#*/}" .
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
